### PR TITLE
Dev v0.1

### PR DESCRIPTION
**Pull request by generationmake**
create rev 0.1

### CODE REVIEW

**Comment by generationmake** [comment]
@aentinger could you please have alook at the schematic and provide some input. Thank you

**Comment by aentinger** [comment]
Hi @generationmake :wave: :coffee: Great work! :rocket: 

I've reviewed the current schematic and suggest the following suggestions:
* Pull-Ups (`10k`) for `BNO085_INT` and `BMP388_INT`
* Possibly (weak) pull-up (`100k`?) on `RESET` (depends if such a pull-up already exists on the MRK board or not)
* If we want to use internal oscillator than I suggest to also connect `CLKSEL1` to GND.
* Do we need to connect `PS0/WAKE` to the MCU too? The following sentence from the datasheet suggests as much:
> After reset the PS0/WAKE signal is used as a ‘wake’ signal taking the BNO080 out of sleep if the host wants
to initiate communication with the BNO080.

**Comment by aentinger** [comment]
Another small plea from my side: on the `MKR VIDOR 4000` Pin D3 is used as CS for the FPGA. Maybe you cab move the `BNO085_CS` to `D5`? Here's a [link to the I/O pins assigned](https://github.com/107-systems/107-Arduino-Viper/blob/master/examples/Viper-Firmware/ViperConst.h#L19-L23) for the Viper Quadcopter so far.

**Comment by generationmake** [comment]
Hi @aentinger 
Thank you for your input. I added your requests to the schematic.

Regarding the wake signal: Supports Arduino wake signals? Or just connect the line to any external interrupt line?

**Comment by aentinger** [comment]
Hi :wave: As I understand it the WAKE signal is a digital input for the BNO085 which is necessary to wake it from deep sleep. I've not looked at the datasheet in detail so I don't know if this can anyway be disabled at startup configuration, in any case both our applications don't require sleeping so it would be probably better to just permanently set it to HIGH?

**Comment by aentinger** [comment]
And can you please get me commit access to this repository? I'd like to add documentation to the README pointing to the Arduino libraries.

**Comment by generationmake** [comment]
@wuehr1999 could you also have a look on this? please. thank you

**Comment by wuehr1999** [comment]
Hi @generationmake,

the design is looking very good already :-)

I agree with @aentinger that the WAKE signal should be HIGH, but I think there should be a possibility to connect this pin to the MCU. Maybe a (solder-)jumper for switching between permanent HIGH and a MCU pin would be the right solution?

There should also be connection headers for UART and I2C so other sensors like GPS modules can be connected for more complex navigation tasks.

As SPI is in use on the board anyway, what do You think about a micro SD-Card slot for logging and exchange of navigation data?

**Comment by generationmake** [comment]
@aentinger and @wuehr1999 
I thought the WAKE signal is an output of BNO085 but that was wrong!
I will add the opportunity to connect it to a digital pin of the Arduino MKR. What do you think of D1?

I will also add additional connectors for UART and SPI.

You could use the MKR SD Proto Shield for SD cards: https://store.arduino.cc/mkr-sd-proto-shield

**Comment by aentinger** [comment]
Also there's the possibility of using the Arduino MKR Zero which comes with onboard SD slot afaik.

**Comment by generationmake** [comment]
Hi @wuehr1999 and @aentinger 
Thank you for your input. I updated the schematic and made the first draft of the layout.
What di you think about it?

**Comment by wuehr1999** [comment]
Hi @generationmake @aentinger 
the layout is looking very good already, I couldn't spot any obvious bugs.
What do You think about making the shield a bit longer so holes for 2.5mm standoffs can be added?

**Comment by aentinger** [comment]
All looking good :100: :rocket:

**Comment by generationmake** [comment]
I made the pcb bigger to fit the Arduino MKR form factor with holes. Any suggestions what to do with the new free space?

**Comment by wuehr1999** [comment]
Hi @generationmake 

I have a few suggestions for the free space (although nothing is a real must-have feature):

- power LED
- silkscreen text (board version + name, pinouts, ...)
- micro SD-Card slot ;-)

**Comment by wuehr1999** [comment]
The wake pin should not be connected at D1, as it will be conflicting with the pinouts of our other shields (ArduHMIShield or ActuatorExtenderI2C). Uncritical pins would be A0 - A1 and A3 - A5...

**Comment by generationmake** [comment]
The datasheet of the BNO085 shows the possibility to add a Bosch BMP280 or BME280 pressure sensor and a CM36686 proximity and ambient light sensor directly to the BNO085 via I2C. So I added the possibility on the shield.
The CM36686 seems to be the same as Vishay VCNL4040. Because there is only data for the VCNL4040 available I added this part.

From my side this project is now finished and ready for production. 
Any comments?

**Comment by aentinger** [comment]
Great project and good work :+1: I'm not finding any immediate issue, but I'd like to announce my desire to get one board with `BMP388`, `BNO085 `and `VCNL4040 `with `BMP388 `and `BNO085 `configured for SPI 😉 Question: I've not looked at the `BMO085` datasheet in detail but would it be possible to access the `BMP388` also via the `BNO085` **I2C bridge**? I imagine that it doesn't really matter what I2C device you connect there unless it follows a certain protocol.

**Comment by generationmake** [comment]
The board was manufactured and tested. Both BMP388 and BNO085 worked fine.

**Comment by generationmake** [comment]
all fine
merge v0.1

**Pull request merged**
